name: Automatic update

on:
  schedule:
    - cron: "54 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up LLVM and Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y lld llvm llvm-dev clang

      - name: Set up Zig
        uses: mlugg/setup-zig@v2

      - name: Fetch latest commit
        run: zig fetch --save=urg_library git+https://github.com/UrgNetwork/urg_library

      - name: Run `zig build`
        run: zig build

      - name: Commit update
        uses: EndBug/add-and-commit@v9
        with:
          add: 'build.zig.zon'
          message: 'Automatic update'

